from PyQt5 import QtCore, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setFixedSize(627, 382)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        self.regular_rhythm_tab = QtWidgets.QWidget()
        self.regular_rhythm_tab.setObjectName("regular_rhythm_tab")
        self.rr_main_groupBox = QtWidgets.QGroupBox(self.regular_rhythm_tab)
        self.rr_main_groupBox.setGeometry(QtCore.QRect(80, 10, 161, 311))
        self.rr_main_groupBox.setObjectName("rr_main_groupBox")
        self.rr_main_dur_comboBox = QtWidgets.QComboBox(self.rr_main_groupBox)
        self.rr_main_dur_comboBox.setGeometry(QtCore.QRect(10, 50, 141, 26))
        self.rr_main_dur_comboBox.setObjectName("rr_main_dur_comboBox")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_comboBox.addItem("")
        self.rr_main_dur_label = QtWidgets.QLabel(self.rr_main_groupBox)
        self.rr_main_dur_label.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.rr_main_dur_label.setObjectName("rr_main_dur_label")
        self.rr_num_of_bars_label = QtWidgets.QLabel(self.rr_main_groupBox)
        self.rr_num_of_bars_label.setGeometry(QtCore.QRect(10, 180, 111, 16))
        self.rr_num_of_bars_label.setObjectName("rr_num_of_bars_label")
        self.rr_num_of_bars_spinBox = QtWidgets.QSpinBox(self.rr_main_groupBox)
        self.rr_num_of_bars_spinBox.setGeometry(QtCore.QRect(10, 200, 121, 24))
        self.rr_num_of_bars_spinBox.setMaximum(1000)
        self.rr_num_of_bars_spinBox.setObjectName("rr_num_of_bars_spinBox")
        self.rr_time_sig_groupBox = QtWidgets.QGroupBox(self.rr_main_groupBox)
        self.rr_time_sig_groupBox.setGeometry(QtCore.QRect(10, 80, 101, 91))
        self.rr_time_sig_groupBox.setObjectName("rr_time_sig_groupBox")
        self.rr_time_sig_first_spinBox = QtWidgets.QSpinBox(self.rr_time_sig_groupBox)
        self.rr_time_sig_first_spinBox.setGeometry(QtCore.QRect(10, 30, 71, 24))
        self.rr_time_sig_first_spinBox.setMaximum(1000)
        self.rr_time_sig_first_spinBox.setObjectName("rr_time_sig_first_spinBox")
        self.rr_time_sig_second_spinBox = QtWidgets.QSpinBox(self.rr_time_sig_groupBox)
        self.rr_time_sig_second_spinBox.setGeometry(QtCore.QRect(10, 60, 71, 24))
        self.rr_time_sig_second_spinBox.setMaximum(1000)
        self.rr_time_sig_second_spinBox.setObjectName("rr_time_sig_second_spinBox")
        self.rr_num_of_staves_spinBox = QtWidgets.QSpinBox(self.rr_main_groupBox)
        self.rr_num_of_staves_spinBox.setGeometry(QtCore.QRect(10, 260, 121, 24))
        self.rr_num_of_staves_spinBox.setMaximum(1000)
        self.rr_num_of_staves_spinBox.setObjectName("rr_num_of_staves_spinBox")
        self.rr_num_of_staves_label = QtWidgets.QLabel(self.rr_main_groupBox)
        self.rr_num_of_staves_label.setGeometry(QtCore.QRect(10, 240, 111, 16))
        self.rr_num_of_staves_label.setObjectName("rr_num_of_staves_label")
        self.rr_div_irreg_checkBox = QtWidgets.QCheckBox(self.regular_rhythm_tab)
        self.rr_div_irreg_checkBox.setEnabled(True)
        self.rr_div_irreg_checkBox.setGeometry(QtCore.QRect(410, 210, 121, 20))
        self.rr_div_irreg_checkBox.setChecked(False)
        self.rr_div_irreg_checkBox.setAutoRepeat(False)
        self.rr_div_irreg_checkBox.setTristate(False)
        self.rr_div_irreg_checkBox.setObjectName("rr_div_irreg_checkBox")
        self.rr_division_checkBox = QtWidgets.QCheckBox(self.regular_rhythm_tab)
        self.rr_division_checkBox.setEnabled(True)
        self.rr_division_checkBox.setGeometry(QtCore.QRect(410, 240, 131, 20))
        self.rr_division_checkBox.setObjectName("rr_division_checkBox")
        self.rr_division_groupBox = QtWidgets.QGroupBox(self.regular_rhythm_tab)
        self.rr_division_groupBox.setEnabled(False)
        self.rr_division_groupBox.setGeometry(QtCore.QRect(250, 10, 301, 181))
        self.rr_division_groupBox.setObjectName("rr_division_groupBox")
        self.rr_div_perc_label = QtWidgets.QLabel(self.rr_division_groupBox)
        self.rr_div_perc_label.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.rr_div_perc_label.setObjectName("rr_div_perc_label")
        self.rr_special_groupBox = QtWidgets.QGroupBox(self.rr_division_groupBox)
        self.rr_special_groupBox.setEnabled(False)
        self.rr_special_groupBox.setGeometry(QtCore.QRect(10, 80, 101, 81))
        self.rr_special_groupBox.setObjectName("rr_special_groupBox")
        self.rr_div_parts_spinBox = QtWidgets.QSpinBox(self.rr_special_groupBox)
        self.rr_div_parts_spinBox.setGeometry(QtCore.QRect(10, 50, 61, 24))
        self.rr_div_parts_spinBox.setMinimum(2)
        self.rr_div_parts_spinBox.setMaximum(4)
        self.rr_div_parts_spinBox.setObjectName("rr_div_parts_spinBox")
        self.rr_div_parts_label = QtWidgets.QLabel(self.rr_special_groupBox)
        self.rr_div_parts_label.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.rr_div_parts_label.setObjectName("rr_div_parts_label")
        self.rr_div_perc_spinBox = QtWidgets.QSpinBox(self.rr_division_groupBox)
        self.rr_div_perc_spinBox.setGeometry(QtCore.QRect(10, 50, 121, 24))
        self.rr_div_perc_spinBox.setMaximum(100)
        self.rr_div_perc_spinBox.setObjectName("rr_div_perc_spinBox")
        self.rr_denom_groupBox = QtWidgets.QGroupBox(self.rr_division_groupBox)
        self.rr_denom_groupBox.setGeometry(QtCore.QRect(150, 20, 91, 141))
        self.rr_denom_groupBox.setObjectName("rr_denom_groupBox")
        self.rr_den_min_label = QtWidgets.QLabel(self.rr_denom_groupBox)
        self.rr_den_min_label.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.rr_den_min_label.setObjectName("rr_den_min_label")
        self.rr_den_max_label = QtWidgets.QLabel(self.rr_denom_groupBox)
        self.rr_den_max_label.setGeometry(QtCore.QRect(10, 80, 31, 16))
        self.rr_den_max_label.setObjectName("rr_den_max_label")
        self.rr_den_min_spinBox = QtWidgets.QSpinBox(self.rr_denom_groupBox)
        self.rr_den_min_spinBox.setGeometry(QtCore.QRect(10, 50, 61, 24))
        self.rr_den_min_spinBox.setMaximum(20)
        self.rr_den_min_spinBox.setObjectName("rr_den_min_spinBox")
        self.rr_den_max_spinBox = QtWidgets.QSpinBox(self.rr_denom_groupBox)
        self.rr_den_max_spinBox.setGeometry(QtCore.QRect(10, 100, 61, 24))
        self.rr_den_max_spinBox.setMaximum(20)
        self.rr_den_max_spinBox.setObjectName("rr_den_max_spinBox")
        self.rr_rests_groupBox = QtWidgets.QGroupBox(self.regular_rhythm_tab)
        self.rr_rests_groupBox.setEnabled(False)
        self.rr_rests_groupBox.setGeometry(QtCore.QRect(250, 190, 151, 91))
        self.rr_rests_groupBox.setObjectName("rr_rests_groupBox")
        self.rr_rests_perc_label = QtWidgets.QLabel(self.rr_rests_groupBox)
        self.rr_rests_perc_label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.rr_rests_perc_label.setObjectName("rr_rests_perc_label")
        self.rr_rests_perc_spinBox = QtWidgets.QSpinBox(self.rr_rests_groupBox)
        self.rr_rests_perc_spinBox.setGeometry(QtCore.QRect(10, 50, 121, 24))
        self.rr_rests_perc_spinBox.setMaximum(100)
        self.rr_rests_perc_spinBox.setObjectName("rr_rests_perc_spinBox")
        self.rr_rests_checkBox = QtWidgets.QCheckBox(self.regular_rhythm_tab)
        self.rr_rests_checkBox.setGeometry(QtCore.QRect(260, 290, 87, 20))
        self.rr_rests_checkBox.setObjectName("rr_rests_checkBox")
        self.rr_reset_button = QtWidgets.QPushButton(self.regular_rhythm_tab)
        self.rr_reset_button.setGeometry(QtCore.QRect(410, 270, 113, 32))
        self.rr_reset_button.setObjectName("rr_reset_button")
        self.rr_generate_button = QtWidgets.QPushButton(self.regular_rhythm_tab)
        self.rr_generate_button.setGeometry(QtCore.QRect(410, 310, 113, 32))
        self.rr_generate_button.setObjectName("rr_generate_button")
        TabWidget.addTab(self.regular_rhythm_tab, "")
        self.irregular_rhythm_tab = QtWidgets.QWidget()
        self.irregular_rhythm_tab.setObjectName("irregular_rhythm_tab")
        self.ir_main_groupBox = QtWidgets.QGroupBox(self.irregular_rhythm_tab)
        self.ir_main_groupBox.setGeometry(QtCore.QRect(40, 20, 151, 151))
        self.ir_main_groupBox.setObjectName("ir_main_groupBox")
        self.ir_num_of_layers_label = QtWidgets.QLabel(self.ir_main_groupBox)
        self.ir_num_of_layers_label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.ir_num_of_layers_label.setObjectName("ir_num_of_layers_label")
        self.ir_num_of_layers_spinBox = QtWidgets.QSpinBox(self.ir_main_groupBox)
        self.ir_num_of_layers_spinBox.setGeometry(QtCore.QRect(10, 50, 111, 24))
        self.ir_num_of_layers_spinBox.setMinimum(1)
        self.ir_num_of_layers_spinBox.setMaximum(4)
        self.ir_num_of_layers_spinBox.setProperty("value", 1)
        self.ir_num_of_layers_spinBox.setObjectName("ir_num_of_layers_spinBox")
        self.ir_num_of_staves_spinBox = QtWidgets.QSpinBox(self.ir_main_groupBox)
        self.ir_num_of_staves_spinBox.setGeometry(QtCore.QRect(10, 110, 111, 24))
        self.ir_num_of_staves_spinBox.setMaximum(1000)
        self.ir_num_of_staves_spinBox.setObjectName("ir_num_of_staves_spinBox")
        self.ir_num_of_staves_label = QtWidgets.QLabel(self.ir_main_groupBox)
        self.ir_num_of_staves_label.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.ir_num_of_staves_label.setObjectName("ir_num_of_staves_label")
        self.ir_generator_groupBox = QtWidgets.QGroupBox(self.irregular_rhythm_tab)
        self.ir_generator_groupBox.setEnabled(False)
        self.ir_generator_groupBox.setGeometry(QtCore.QRect(200, 20, 381, 211))
        self.ir_generator_groupBox.setObjectName("ir_generator_groupBox")
        self.ir_num_of_bars_spinBox = QtWidgets.QSpinBox(self.ir_generator_groupBox)
        self.ir_num_of_bars_spinBox.setGeometry(QtCore.QRect(10, 50, 121, 24))
        self.ir_num_of_bars_spinBox.setMaximum(1000)
        self.ir_num_of_bars_spinBox.setObjectName("ir_num_of_bars_spinBox")
        self.ir_num_of_bars_label = QtWidgets.QLabel(self.ir_generator_groupBox)
        self.ir_num_of_bars_label.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.ir_num_of_bars_label.setObjectName("ir_num_of_bars_label")
        self.ir_time_sig_groupBox = QtWidgets.QGroupBox(self.ir_generator_groupBox)
        self.ir_time_sig_groupBox.setEnabled(False)
        self.ir_time_sig_groupBox.setGeometry(QtCore.QRect(10, 80, 101, 91))
        self.ir_time_sig_groupBox.setObjectName("ir_time_sig_groupBox")
        self.ir_time_sig_first_spinBox = QtWidgets.QSpinBox(self.ir_time_sig_groupBox)
        self.ir_time_sig_first_spinBox.setGeometry(QtCore.QRect(10, 30, 71, 24))
        self.ir_time_sig_first_spinBox.setMaximum(1000)
        self.ir_time_sig_first_spinBox.setObjectName("ir_time_sig_first_spinBox")
        self.ir_time_sig_second_spinBox = QtWidgets.QSpinBox(self.ir_time_sig_groupBox)
        self.ir_time_sig_second_spinBox.setGeometry(QtCore.QRect(10, 60, 71, 24))
        self.ir_time_sig_second_spinBox.setMaximum(1000)
        self.ir_time_sig_second_spinBox.setObjectName("ir_time_sig_second_spinBox")
        self.ir_single_time_sig_checkBox = QtWidgets.QCheckBox(self.ir_generator_groupBox)
        self.ir_single_time_sig_checkBox.setGeometry(QtCore.QRect(10, 180, 151, 20))
        self.ir_single_time_sig_checkBox.setObjectName("ir_single_time_sig_checkBox")
        self.ir_div_last_layer_checkBox = QtWidgets.QCheckBox(self.ir_generator_groupBox)
        self.ir_div_last_layer_checkBox.setGeometry(QtCore.QRect(180, 180, 121, 20))
        self.ir_div_last_layer_checkBox.setChecked(True)
        self.ir_div_last_layer_checkBox.setObjectName("ir_div_last_layer_checkBox")
        self.ir_min_val_label = QtWidgets.QLabel(self.ir_generator_groupBox)
        self.ir_min_val_label.setGeometry(QtCore.QRect(150, 40, 71, 16))
        self.ir_min_val_label.setObjectName("ir_min_val_label")
        self.ir_max_val_label = QtWidgets.QLabel(self.ir_generator_groupBox)
        self.ir_max_val_label.setGeometry(QtCore.QRect(150, 100, 71, 16))
        self.ir_max_val_label.setObjectName("ir_max_val_label")
        self.ir_min_val_spinBox = QtWidgets.QSpinBox(self.ir_generator_groupBox)
        self.ir_min_val_spinBox.setGeometry(QtCore.QRect(150, 60, 71, 24))
        self.ir_min_val_spinBox.setMaximum(6)
        self.ir_min_val_spinBox.setObjectName("ir_min_val_spinBox")
        self.ir_max_val_spinBox = QtWidgets.QSpinBox(self.ir_generator_groupBox)
        self.ir_max_val_spinBox.setGeometry(QtCore.QRect(150, 120, 71, 24))
        self.ir_max_val_spinBox.setMaximum(6)
        self.ir_max_val_spinBox.setObjectName("ir_max_val_spinBox")
        self.ir_rests_groupBox = QtWidgets.QGroupBox(self.ir_generator_groupBox)
        self.ir_rests_groupBox.setEnabled(False)
        self.ir_rests_groupBox.setGeometry(QtCore.QRect(240, 30, 131, 91))
        self.ir_rests_groupBox.setObjectName("ir_rests_groupBox")
        self.ir_rests_perc_label = QtWidgets.QLabel(self.ir_rests_groupBox)
        self.ir_rests_perc_label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.ir_rests_perc_label.setObjectName("ir_rests_perc_label")
        self.ir_rests_perc_spinBox = QtWidgets.QSpinBox(self.ir_rests_groupBox)
        self.ir_rests_perc_spinBox.setGeometry(QtCore.QRect(10, 50, 111, 24))
        self.ir_rests_perc_spinBox.setMaximum(100)
        self.ir_rests_perc_spinBox.setObjectName("ir_rests_perc_spinBox")
        self.ir_rests_checkBox = QtWidgets.QCheckBox(self.ir_generator_groupBox)
        self.ir_rests_checkBox.setGeometry(QtCore.QRect(250, 130, 87, 20))
        self.ir_rests_checkBox.setObjectName("ir_rests_checkBox")
        self.ir_reset_button = QtWidgets.QPushButton(self.irregular_rhythm_tab)
        self.ir_reset_button.setGeometry(QtCore.QRect(320, 300, 113, 32))
        self.ir_reset_button.setObjectName("ir_reset_button")
        self.ir_generate_button = QtWidgets.QPushButton(self.irregular_rhythm_tab)
        self.ir_generate_button.setEnabled(False)
        self.ir_generate_button.setGeometry(QtCore.QRect(450, 300, 113, 32))
        self.ir_generate_button.setObjectName("ir_generate_button")
        self.ir_create_button = QtWidgets.QPushButton(self.irregular_rhythm_tab)
        self.ir_create_button.setEnabled(False)
        self.ir_create_button.setGeometry(QtCore.QRect(40, 300, 113, 32))
        self.ir_create_button.setObjectName("ir_create_button")
        self.ir_get_from_excel_button = QtWidgets.QPushButton(self.irregular_rhythm_tab)
        self.ir_get_from_excel_button.setEnabled(False)
        self.ir_get_from_excel_button.setGeometry(QtCore.QRect(160, 300, 113, 32))
        self.ir_get_from_excel_button.setObjectName("ir_get_from_excel_button")
        self.ir_operation_groupBox = QtWidgets.QGroupBox(self.irregular_rhythm_tab)
        self.ir_operation_groupBox.setGeometry(QtCore.QRect(40, 180, 151, 91))
        self.ir_operation_groupBox.setObjectName("ir_operation_groupBox")
        self.ir_create_radioButton = QtWidgets.QRadioButton(self.ir_operation_groupBox)
        self.ir_create_radioButton.setGeometry(QtCore.QRect(10, 30, 71, 20))
        self.ir_create_radioButton.setObjectName("ir_create_radioButton")
        self.ir_op_radiobuttonGroup = QtWidgets.QButtonGroup(TabWidget)
        self.ir_op_radiobuttonGroup.setObjectName("ir_op_radiobuttonGroup")
        self.ir_op_radiobuttonGroup.addButton(self.ir_create_radioButton)
        self.ir_generate_radioButton = QtWidgets.QRadioButton(self.ir_operation_groupBox)
        self.ir_generate_radioButton.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.ir_generate_radioButton.setObjectName("ir_generate_radioButton")
        self.ir_op_radiobuttonGroup.addButton(self.ir_generate_radioButton)
        self.ir_time_sig_den_label = QtWidgets.QLabel(self.irregular_rhythm_tab)
        self.ir_time_sig_den_label.setGeometry(QtCore.QRect(210, 240, 181, 16))
        self.ir_time_sig_den_label.setObjectName("ir_time_sig_den_label")
        self.ir_time_sig_den_spinBox = QtWidgets.QSpinBox(self.irregular_rhythm_tab)
        self.ir_time_sig_den_spinBox.setGeometry(QtCore.QRect(210, 260, 121, 24))
        self.ir_time_sig_den_spinBox.setMaximum(1000)
        self.ir_time_sig_den_spinBox.setObjectName("ir_time_sig_den_spinBox")
        TabWidget.addTab(self.irregular_rhythm_tab, "")
        self.phase_rhythm_tab = QtWidgets.QWidget()
        self.phase_rhythm_tab.setObjectName("phase_rhythm_tab")
        self.pr_main_groupBox = QtWidgets.QGroupBox(self.phase_rhythm_tab)
        self.pr_main_groupBox.setGeometry(QtCore.QRect(20, 10, 241, 191))
        self.pr_main_groupBox.setObjectName("pr_main_groupBox")
        self.pr_num_of_bars_label = QtWidgets.QLabel(self.pr_main_groupBox)
        self.pr_num_of_bars_label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.pr_num_of_bars_label.setObjectName("pr_num_of_bars_label")
        self.pr_num_of_bars_spinBox = QtWidgets.QSpinBox(self.pr_main_groupBox)
        self.pr_num_of_bars_spinBox.setGeometry(QtCore.QRect(10, 50, 121, 24))
        self.pr_num_of_bars_spinBox.setMaximum(1000)
        self.pr_num_of_bars_spinBox.setObjectName("pr_num_of_bars_spinBox")
        self.pr_time_sig_groupBox = QtWidgets.QGroupBox(self.pr_main_groupBox)
        self.pr_time_sig_groupBox.setGeometry(QtCore.QRect(10, 80, 101, 91))
        self.pr_time_sig_groupBox.setObjectName("pr_time_sig_groupBox")
        self.pr_time_sig_first_spinBox = QtWidgets.QSpinBox(self.pr_time_sig_groupBox)
        self.pr_time_sig_first_spinBox.setGeometry(QtCore.QRect(10, 30, 71, 24))
        self.pr_time_sig_first_spinBox.setMaximum(1000)
        self.pr_time_sig_first_spinBox.setObjectName("pr_time_sig_first_spinBox")
        self.pr_time_sig_second_spinBox = QtWidgets.QSpinBox(self.pr_time_sig_groupBox)
        self.pr_time_sig_second_spinBox.setGeometry(QtCore.QRect(10, 60, 71, 24))
        self.pr_time_sig_second_spinBox.setMaximum(1000)
        self.pr_time_sig_second_spinBox.setObjectName("pr_time_sig_second_spinBox")
        self.pr_phase_groupBox = QtWidgets.QGroupBox(self.pr_main_groupBox)
        self.pr_phase_groupBox.setGeometry(QtCore.QRect(140, 20, 91, 151))
        self.pr_phase_groupBox.setObjectName("pr_phase_groupBox")
        self.pr_min_phase_spinBox = QtWidgets.QSpinBox(self.pr_phase_groupBox)
        self.pr_min_phase_spinBox.setGeometry(QtCore.QRect(10, 50, 61, 24))
        self.pr_min_phase_spinBox.setMaximum(512)
        self.pr_min_phase_spinBox.setObjectName("pr_min_phase_spinBox")
        self.pr_max_phase_spinBox = QtWidgets.QSpinBox(self.pr_phase_groupBox)
        self.pr_max_phase_spinBox.setGeometry(QtCore.QRect(10, 110, 61, 24))
        self.pr_max_phase_spinBox.setMaximum(512)
        self.pr_max_phase_spinBox.setObjectName("pr_max_phase_spinBox")
        self.pr_max_phase_label = QtWidgets.QLabel(self.pr_phase_groupBox)
        self.pr_max_phase_label.setGeometry(QtCore.QRect(10, 90, 31, 16))
        self.pr_max_phase_label.setObjectName("pr_max_phase_label")
        self.pr_min_phase_label = QtWidgets.QLabel(self.pr_phase_groupBox)
        self.pr_min_phase_label.setGeometry(QtCore.QRect(10, 30, 31, 16))
        self.pr_min_phase_label.setObjectName("pr_min_phase_label")
        self.pr_rand_phase_gen_groupBox = QtWidgets.QGroupBox(self.phase_rhythm_tab)
        self.pr_rand_phase_gen_groupBox.setEnabled(False)
        self.pr_rand_phase_gen_groupBox.setGeometry(QtCore.QRect(270, 10, 331, 191))
        self.pr_rand_phase_gen_groupBox.setObjectName("pr_rand_phase_gen_groupBox")
        self.pr_time_sig_lst_label = QtWidgets.QLabel(self.pr_rand_phase_gen_groupBox)
        self.pr_time_sig_lst_label.setEnabled(False)
        self.pr_time_sig_lst_label.setGeometry(QtCore.QRect(10, 90, 131, 16))
        self.pr_time_sig_lst_label.setObjectName("pr_time_sig_lst_label")
        self.pr_time_sig_lst_lineEdit = QtWidgets.QLineEdit(self.pr_rand_phase_gen_groupBox)
        self.pr_time_sig_lst_lineEdit.setEnabled(False)
        self.pr_time_sig_lst_lineEdit.setGeometry(QtCore.QRect(10, 110, 141, 21))
        self.pr_time_sig_lst_lineEdit.setObjectName("pr_time_sig_lst_lineEdit")
        self.pr_diff_time_sig_checkBox = QtWidgets.QCheckBox(self.pr_rand_phase_gen_groupBox)
        self.pr_diff_time_sig_checkBox.setGeometry(QtCore.QRect(10, 150, 181, 20))
        self.pr_diff_time_sig_checkBox.setObjectName("pr_diff_time_sig_checkBox")
        self.pr_rests_groupBox = QtWidgets.QGroupBox(self.pr_rand_phase_gen_groupBox)
        self.pr_rests_groupBox.setEnabled(False)
        self.pr_rests_groupBox.setGeometry(QtCore.QRect(160, 20, 151, 91))
        self.pr_rests_groupBox.setObjectName("pr_rests_groupBox")
        self.pr_rests_perc_label = QtWidgets.QLabel(self.pr_rests_groupBox)
        self.pr_rests_perc_label.setGeometry(QtCore.QRect(10, 30, 111, 16))
        self.pr_rests_perc_label.setObjectName("pr_rests_perc_label")
        self.pr_rests_perc_spinBox = QtWidgets.QSpinBox(self.pr_rests_groupBox)
        self.pr_rests_perc_spinBox.setGeometry(QtCore.QRect(10, 50, 91, 24))
        self.pr_rests_perc_spinBox.setMaximum(100)
        self.pr_rests_perc_spinBox.setObjectName("pr_rests_perc_spinBox")
        self.pr_rests_checkBox = QtWidgets.QCheckBox(self.pr_rand_phase_gen_groupBox)
        self.pr_rests_checkBox.setGeometry(QtCore.QRect(170, 120, 87, 20))
        self.pr_rests_checkBox.setObjectName("pr_rests_checkBox")
        self.pr_num_of_staves_spinBox = QtWidgets.QSpinBox(self.pr_rand_phase_gen_groupBox)
        self.pr_num_of_staves_spinBox.setGeometry(QtCore.QRect(10, 50, 121, 24))
        self.pr_num_of_staves_spinBox.setMaximum(1000)
        self.pr_num_of_staves_spinBox.setObjectName("pr_num_of_staves_spinBox")
        self.pr_num_of_staves_label = QtWidgets.QLabel(self.pr_rand_phase_gen_groupBox)
        self.pr_num_of_staves_label.setGeometry(QtCore.QRect(10, 30, 121, 16))
        self.pr_num_of_staves_label.setObjectName("pr_num_of_staves_label")
        self.pr_place_points_groupBox = QtWidgets.QGroupBox(self.phase_rhythm_tab)
        self.pr_place_points_groupBox.setEnabled(False)
        self.pr_place_points_groupBox.setGeometry(QtCore.QRect(270, 210, 191, 111))
        self.pr_place_points_groupBox.setObjectName("pr_place_points_groupBox")
        self.pr_num_of_imp_label = QtWidgets.QLabel(self.pr_place_points_groupBox)
        self.pr_num_of_imp_label.setGeometry(QtCore.QRect(10, 30, 131, 16))
        self.pr_num_of_imp_label.setObjectName("pr_num_of_imp_label")
        self.pr_num_of_imp_spinBox = QtWidgets.QSpinBox(self.pr_place_points_groupBox)
        self.pr_num_of_imp_spinBox.setGeometry(QtCore.QRect(10, 50, 121, 24))
        self.pr_num_of_imp_spinBox.setMaximum(1000)
        self.pr_num_of_imp_spinBox.setObjectName("pr_num_of_imp_spinBox")
        self.pr_phase_filter_checkBox = QtWidgets.QCheckBox(self.pr_place_points_groupBox)
        self.pr_phase_filter_checkBox.setGeometry(QtCore.QRect(10, 80, 171, 20))
        self.pr_phase_filter_checkBox.setObjectName("pr_phase_filter_checkBox")
        self.pr_reset_button = QtWidgets.QPushButton(self.phase_rhythm_tab)
        self.pr_reset_button.setGeometry(QtCore.QRect(480, 230, 113, 32))
        self.pr_reset_button.setObjectName("pr_reset_button")
        self.pr_generate_button = QtWidgets.QPushButton(self.phase_rhythm_tab)
        self.pr_generate_button.setEnabled(False)
        self.pr_generate_button.setGeometry(QtCore.QRect(480, 270, 113, 32))
        self.pr_generate_button.setObjectName("pr_generate_button")
        self.pr_operation_groupBox = QtWidgets.QGroupBox(self.phase_rhythm_tab)
        self.pr_operation_groupBox.setGeometry(QtCore.QRect(20, 210, 241, 111))
        self.pr_operation_groupBox.setObjectName("pr_operation_groupBox")
        self.pr_gen_rand_ph_radioButton = QtWidgets.QRadioButton(self.pr_operation_groupBox)
        self.pr_gen_rand_ph_radioButton.setGeometry(QtCore.QRect(10, 30, 181, 20))
        self.pr_gen_rand_ph_radioButton.setObjectName("pr_gen_rand_ph_radioButton")
        self.pr_op_radiobuttonGroup = QtWidgets.QButtonGroup(TabWidget)
        self.pr_op_radiobuttonGroup.setObjectName("pr_op_radiobuttonGroup")
        self.pr_op_radiobuttonGroup.addButton(self.pr_gen_rand_ph_radioButton)
        self.pr_place_points_radioButton = QtWidgets.QRadioButton(self.pr_operation_groupBox)
        self.pr_place_points_radioButton.setGeometry(QtCore.QRect(10, 60, 101, 20))
        self.pr_place_points_radioButton.setObjectName("pr_place_points_radioButton")
        self.pr_op_radiobuttonGroup.addButton(self.pr_place_points_radioButton)
        TabWidget.addTab(self.phase_rhythm_tab, "")
        self.place_events_tab = QtWidgets.QWidget()
        self.place_events_tab.setObjectName("place_events_tab")
        self.pe_main_groupBox = QtWidgets.QGroupBox(self.place_events_tab)
        self.pe_main_groupBox.setGeometry(QtCore.QRect(140, 30, 351, 251))
        self.pe_main_groupBox.setObjectName("pe_main_groupBox")
        self.pe_main_dur_comboBox = QtWidgets.QComboBox(self.pe_main_groupBox)
        self.pe_main_dur_comboBox.setGeometry(QtCore.QRect(10, 50, 141, 26))
        self.pe_main_dur_comboBox.setObjectName("pe_main_dur_comboBox")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_comboBox.addItem("")
        self.pe_main_dur_label = QtWidgets.QLabel(self.pe_main_groupBox)
        self.pe_main_dur_label.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.pe_main_dur_label.setObjectName("pe_main_dur_label")
        self.pe_num_of_bars_label = QtWidgets.QLabel(self.pe_main_groupBox)
        self.pe_num_of_bars_label.setGeometry(QtCore.QRect(10, 180, 111, 16))
        self.pe_num_of_bars_label.setObjectName("pe_num_of_bars_label")
        self.pe_num_of_bars_spinBox = QtWidgets.QSpinBox(self.pe_main_groupBox)
        self.pe_num_of_bars_spinBox.setGeometry(QtCore.QRect(10, 200, 121, 24))
        self.pe_num_of_bars_spinBox.setMaximum(1000)
        self.pe_num_of_bars_spinBox.setObjectName("pe_num_of_bars_spinBox")
        self.pe_time_sig_groupBox = QtWidgets.QGroupBox(self.pe_main_groupBox)
        self.pe_time_sig_groupBox.setGeometry(QtCore.QRect(10, 80, 101, 91))
        self.pe_time_sig_groupBox.setObjectName("pe_time_sig_groupBox")
        self.pe_time_sig_first_spinBox = QtWidgets.QSpinBox(self.pe_time_sig_groupBox)
        self.pe_time_sig_first_spinBox.setGeometry(QtCore.QRect(10, 30, 71, 24))
        self.pe_time_sig_first_spinBox.setMaximum(1000)
        self.pe_time_sig_first_spinBox.setObjectName("pe_time_sig_first_spinBox")
        self.pe_time_sig_second_spinBox = QtWidgets.QSpinBox(self.pe_time_sig_groupBox)
        self.pe_time_sig_second_spinBox.setGeometry(QtCore.QRect(10, 60, 71, 24))
        self.pe_time_sig_second_spinBox.setMaximum(1000)
        self.pe_time_sig_second_spinBox.setObjectName("pe_time_sig_second_spinBox")
        self.pe_num_of_staves_label = QtWidgets.QLabel(self.pe_main_groupBox)
        self.pe_num_of_staves_label.setGeometry(QtCore.QRect(170, 30, 111, 16))
        self.pe_num_of_staves_label.setObjectName("pe_num_of_staves_label")
        self.pe_durs_of_ev_label = QtWidgets.QLabel(self.pe_main_groupBox)
        self.pe_durs_of_ev_label.setGeometry(QtCore.QRect(170, 90, 131, 16))
        self.pe_durs_of_ev_label.setObjectName("pe_durs_of_ev_label")
        self.pe_durs_of_ev_lineEdit = QtWidgets.QLineEdit(self.pe_main_groupBox)
        self.pe_durs_of_ev_lineEdit.setGeometry(QtCore.QRect(170, 110, 141, 21))
        self.pe_durs_of_ev_lineEdit.setObjectName("pe_durs_of_ev_lineEdit")
        self.pe_num_of_staves_spinBox = QtWidgets.QSpinBox(self.pe_main_groupBox)
        self.pe_num_of_staves_spinBox.setGeometry(QtCore.QRect(170, 50, 121, 24))
        self.pe_num_of_staves_spinBox.setMaximum(1000)
        self.pe_num_of_staves_spinBox.setObjectName("pe_num_of_staves_spinBox")
        self.pe_generate_button = QtWidgets.QPushButton(self.pe_main_groupBox)
        self.pe_generate_button.setGeometry(QtCore.QRect(170, 190, 113, 32))
        self.pe_generate_button.setObjectName("pe_generate_button")
        self.pe_reset_button = QtWidgets.QPushButton(self.pe_main_groupBox)
        self.pe_reset_button.setGeometry(QtCore.QRect(170, 150, 113, 32))
        self.pe_reset_button.setObjectName("pe_reset_button")
        TabWidget.addTab(self.place_events_tab, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        self.rr_division_checkBox.clicked['bool'].connect(self.rr_division_groupBox.setEnabled)  # type: ignore
        self.rr_rests_checkBox.clicked['bool'].connect(self.rr_rests_groupBox.setEnabled)  # type: ignore
        self.rr_div_irreg_checkBox.clicked['bool'].connect(self.rr_special_groupBox.setEnabled)  # type: ignore
        self.rr_main_dur_comboBox.activated.connect(self.rr_division_enabled)
        self.rr_reset_button.clicked.connect(self.rr_reset)
        self.ir_generate_radioButton.toggled['bool'].connect(self.ir_generator_groupBox.setEnabled)  # type: ignore
        self.ir_rests_checkBox.clicked['bool'].connect(self.ir_rests_groupBox.setEnabled)  # type: ignore
        self.ir_generate_radioButton.toggled['bool'].connect(self.ir_generate_button.setEnabled)  # type: ignore
        self.ir_create_radioButton.toggled['bool'].connect(self.ir_create_button.setEnabled)  # type: ignore
        self.ir_create_radioButton.toggled['bool'].connect(self.ir_get_from_excel_button.setEnabled)  # type: ignore
        self.ir_single_time_sig_checkBox.clicked['bool'].connect(self.ir_time_sig_groupBox.setEnabled)  # type: ignore
        self.ir_single_time_sig_checkBox.clicked['bool'].connect(
            self.ir_time_sig_den_spinBox.setDisabled)  # type: ignore
        self.ir_single_time_sig_checkBox.clicked['bool'].connect(self.ir_time_sig_den_label.setDisabled)  # type: ignore
        self.ir_create_radioButton.clicked.connect(self.ir_time_sig_enabled)
        self.ir_reset_button.clicked.connect(self.ir_reset)
        self.pr_rests_checkBox.clicked['bool'].connect(self.pr_rests_groupBox.setEnabled)  # type: ignore
        self.pr_place_points_radioButton.toggled['bool'].connect(
            self.pr_place_points_groupBox.setEnabled)  # type: ignore
        self.pr_place_points_radioButton.toggled['bool'].connect(self.pr_time_sig_enabled)
        self.pr_gen_rand_ph_radioButton.toggled['bool'].connect(
            self.pr_rand_phase_gen_groupBox.setEnabled)  # type: ignore
        self.pr_diff_time_sig_checkBox.clicked['bool'].connect(self.pr_num_of_bars_label.setDisabled)  # type: ignore
        self.pr_diff_time_sig_checkBox.clicked['bool'].connect(self.pr_num_of_bars_spinBox.setDisabled)  # type: ignore
        self.pr_diff_time_sig_checkBox.clicked['bool'].connect(self.pr_time_sig_groupBox.setDisabled)  # type: ignore
        self.pr_diff_time_sig_checkBox.clicked['bool'].connect(self.pr_time_sig_lst_label.setEnabled)  # type: ignore
        self.pr_diff_time_sig_checkBox.clicked['bool'].connect(self.pr_time_sig_lst_lineEdit.setEnabled)  # type: ignore
        self.pr_gen_rand_ph_radioButton.toggled['bool'].connect(self.pr_generate_button.setEnabled)  # type: ignore
        self.pr_place_points_radioButton.toggled['bool'].connect(self.pr_generate_button.setEnabled)  # type: ignore
        self.pr_reset_button.clicked.connect(self.pr_reset)
        self.pe_reset_button.clicked.connect(self.pe_reset)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "Random rhythm generator"))
        self.rr_main_groupBox.setTitle(_translate("TabWidget", "Main"))
        self.rr_main_dur_comboBox.setItemText(0, _translate("TabWidget", "1/1"))
        self.rr_main_dur_comboBox.setItemText(1, _translate("TabWidget", "1/2"))
        self.rr_main_dur_comboBox.setItemText(2, _translate("TabWidget", "1/3"))
        self.rr_main_dur_comboBox.setItemText(3, _translate("TabWidget", "1/4"))
        self.rr_main_dur_comboBox.setItemText(4, _translate("TabWidget", "1/5"))
        self.rr_main_dur_comboBox.setItemText(5, _translate("TabWidget", "1/6"))
        self.rr_main_dur_comboBox.setItemText(6, _translate("TabWidget", "1/7"))
        self.rr_main_dur_comboBox.setItemText(7, _translate("TabWidget", "1/8"))
        self.rr_main_dur_comboBox.setItemText(8, _translate("TabWidget", "1/9"))
        self.rr_main_dur_comboBox.setItemText(9, _translate("TabWidget", "1/10"))
        self.rr_main_dur_comboBox.setItemText(10, _translate("TabWidget", "1/11"))
        self.rr_main_dur_comboBox.setItemText(11, _translate("TabWidget", "1/12"))
        self.rr_main_dur_comboBox.setItemText(12, _translate("TabWidget", "1/13"))
        self.rr_main_dur_comboBox.setItemText(13, _translate("TabWidget", "1/14"))
        self.rr_main_dur_comboBox.setItemText(14, _translate("TabWidget", "1/15"))
        self.rr_main_dur_comboBox.setItemText(15, _translate("TabWidget", "1/16"))
        self.rr_main_dur_comboBox.setItemText(16, _translate("TabWidget", "1/17"))
        self.rr_main_dur_comboBox.setItemText(17, _translate("TabWidget", "1/18"))
        self.rr_main_dur_comboBox.setItemText(18, _translate("TabWidget", "1/19"))
        self.rr_main_dur_comboBox.setItemText(19, _translate("TabWidget", "1/20"))
        self.rr_main_dur_comboBox.setItemText(20, _translate("TabWidget", "1/21"))
        self.rr_main_dur_comboBox.setItemText(21, _translate("TabWidget", "1/22"))
        self.rr_main_dur_comboBox.setItemText(22, _translate("TabWidget", "1/23"))
        self.rr_main_dur_comboBox.setItemText(23, _translate("TabWidget", "1/24"))
        self.rr_main_dur_label.setText(_translate("TabWidget", "Fundamental duration:"))
        self.rr_num_of_bars_label.setText(_translate("TabWidget", "Number of bars:"))
        self.rr_time_sig_groupBox.setTitle(_translate("TabWidget", "Time signature"))
        self.rr_num_of_staves_label.setText(_translate("TabWidget", "Number of staves:"))
        self.rr_div_irreg_checkBox.setText(_translate("TabWidget", "Divide irregular"))
        self.rr_division_checkBox.setText(_translate("TabWidget", "Divide main beats"))
        self.rr_division_groupBox.setTitle(_translate("TabWidget", "Division"))
        self.rr_div_perc_label.setText(_translate("TabWidget", "Division percentage:"))
        self.rr_special_groupBox.setTitle(_translate("TabWidget", "Special"))
        self.rr_div_parts_label.setText(_translate("TabWidget", "By parts:"))
        self.rr_denom_groupBox.setTitle(_translate("TabWidget", "Denominator"))
        self.rr_den_min_label.setText(_translate("TabWidget", "Min:"))
        self.rr_den_max_label.setText(_translate("TabWidget", "Max:"))
        self.rr_rests_groupBox.setTitle(_translate("TabWidget", "Rests"))
        self.rr_rests_perc_label.setText(_translate("TabWidget", "Rests percentage:"))
        self.rr_rests_checkBox.setText(_translate("TabWidget", "Add rests"))
        self.rr_reset_button.setText(_translate("TabWidget", "Reset"))
        self.rr_generate_button.setText(_translate("TabWidget", "Generate"))
        TabWidget.setTabText(TabWidget.indexOf(self.regular_rhythm_tab), _translate("TabWidget", "Regular rhythm"))
        self.ir_main_groupBox.setTitle(_translate("TabWidget", "Main"))
        self.ir_num_of_layers_label.setText(_translate("TabWidget", "Number of layers:"))
        self.ir_num_of_staves_label.setText(_translate("TabWidget", "Number of staves:"))
        self.ir_generator_groupBox.setTitle(_translate("TabWidget", "Generator"))
        self.ir_num_of_bars_label.setText(_translate("TabWidget", "Number of bars:"))
        self.ir_time_sig_groupBox.setTitle(_translate("TabWidget", "Time signature"))
        self.ir_single_time_sig_checkBox.setText(_translate("TabWidget", "Single time signature"))
        self.ir_div_last_layer_checkBox.setText(_translate("TabWidget", "Divide last layer"))
        self.ir_min_val_label.setText(_translate("TabWidget", "Min value:"))
        self.ir_max_val_label.setText(_translate("TabWidget", "Max value:"))
        self.ir_rests_groupBox.setTitle(_translate("TabWidget", "Rests"))
        self.ir_rests_perc_label.setText(_translate("TabWidget", "Rests percentage:"))
        self.ir_rests_checkBox.setText(_translate("TabWidget", "Add rests"))
        self.ir_reset_button.setText(_translate("TabWidget", "Reset"))
        self.ir_generate_button.setText(_translate("TabWidget", "Generate"))
        self.ir_create_button.setText(_translate("TabWidget", "Create"))
        self.ir_get_from_excel_button.setText(_translate("TabWidget", "Get from Excel"))
        self.ir_operation_groupBox.setTitle(_translate("TabWidget", "Operation"))
        self.ir_create_radioButton.setText(_translate("TabWidget", "Create"))
        self.ir_generate_radioButton.setText(_translate("TabWidget", "Generate"))
        self.ir_time_sig_den_label.setText(_translate("TabWidget", "Time signature denominator:"))
        TabWidget.setTabText(TabWidget.indexOf(self.irregular_rhythm_tab), _translate("TabWidget", "Irregular Rhythm"))
        self.pr_main_groupBox.setTitle(_translate("TabWidget", "Main"))
        self.pr_num_of_bars_label.setText(_translate("TabWidget", "Number of bars:"))
        self.pr_time_sig_groupBox.setTitle(_translate("TabWidget", "Time signature"))
        self.pr_phase_groupBox.setTitle(_translate("TabWidget", "Phase"))
        self.pr_max_phase_label.setText(_translate("TabWidget", "Max:"))
        self.pr_min_phase_label.setText(_translate("TabWidget", "Min:"))
        self.pr_rand_phase_gen_groupBox.setTitle(_translate("TabWidget", "Random phases generator"))
        self.pr_time_sig_lst_label.setText(_translate("TabWidget", "Time signatures list:"))
        self.pr_diff_time_sig_checkBox.setText(_translate("TabWidget", "Different time signatures"))
        self.pr_rests_groupBox.setTitle(_translate("TabWidget", "Rests"))
        self.pr_rests_perc_label.setText(_translate("TabWidget", "Rests percentage:"))
        self.pr_rests_checkBox.setText(_translate("TabWidget", "Add rests"))
        self.pr_num_of_staves_label.setText(_translate("TabWidget", "Number of staves:"))
        self.pr_place_points_groupBox.setTitle(_translate("TabWidget", "Place points"))
        self.pr_num_of_imp_label.setText(_translate("TabWidget", "Number of impulses:"))
        self.pr_phase_filter_checkBox.setText(_translate("TabWidget", "Remove unused phases"))
        self.pr_reset_button.setText(_translate("TabWidget", "Reset"))
        self.pr_generate_button.setText(_translate("TabWidget", "Generate"))
        self.pr_operation_groupBox.setTitle(_translate("TabWidget", "Operation"))
        self.pr_gen_rand_ph_radioButton.setText(_translate("TabWidget", "Generate random phases"))
        self.pr_place_points_radioButton.setText(_translate("TabWidget", "Place points"))
        TabWidget.setTabText(TabWidget.indexOf(self.phase_rhythm_tab), _translate("TabWidget", "Phase rhythm"))
        self.pe_main_groupBox.setTitle(_translate("TabWidget", "Main"))
        self.pe_main_dur_comboBox.setItemText(0, _translate("TabWidget", "1/1"))
        self.pe_main_dur_comboBox.setItemText(1, _translate("TabWidget", "1/2"))
        self.pe_main_dur_comboBox.setItemText(2, _translate("TabWidget", "1/3"))
        self.pe_main_dur_comboBox.setItemText(3, _translate("TabWidget", "1/4"))
        self.pe_main_dur_comboBox.setItemText(4, _translate("TabWidget", "1/5"))
        self.pe_main_dur_comboBox.setItemText(5, _translate("TabWidget", "1/6"))
        self.pe_main_dur_comboBox.setItemText(6, _translate("TabWidget", "1/7"))
        self.pe_main_dur_comboBox.setItemText(7, _translate("TabWidget", "1/8"))
        self.pe_main_dur_comboBox.setItemText(8, _translate("TabWidget", "1/9"))
        self.pe_main_dur_comboBox.setItemText(9, _translate("TabWidget", "1/10"))
        self.pe_main_dur_comboBox.setItemText(10, _translate("TabWidget", "1/11"))
        self.pe_main_dur_comboBox.setItemText(11, _translate("TabWidget", "1/12"))
        self.pe_main_dur_comboBox.setItemText(12, _translate("TabWidget", "1/13"))
        self.pe_main_dur_comboBox.setItemText(13, _translate("TabWidget", "1/14"))
        self.pe_main_dur_comboBox.setItemText(14, _translate("TabWidget", "1/15"))
        self.pe_main_dur_comboBox.setItemText(15, _translate("TabWidget", "1/16"))
        self.pe_main_dur_comboBox.setItemText(16, _translate("TabWidget", "1/17"))
        self.pe_main_dur_comboBox.setItemText(17, _translate("TabWidget", "1/18"))
        self.pe_main_dur_comboBox.setItemText(18, _translate("TabWidget", "1/19"))
        self.pe_main_dur_comboBox.setItemText(19, _translate("TabWidget", "1/20"))
        self.pe_main_dur_comboBox.setItemText(20, _translate("TabWidget", "1/21"))
        self.pe_main_dur_comboBox.setItemText(21, _translate("TabWidget", "1/22"))
        self.pe_main_dur_comboBox.setItemText(22, _translate("TabWidget", "1/23"))
        self.pe_main_dur_comboBox.setItemText(23, _translate("TabWidget", "1/24"))
        self.pe_main_dur_label.setText(_translate("TabWidget", "Fundamental duration:"))
        self.pe_num_of_bars_label.setText(_translate("TabWidget", "Number of bars:"))
        self.pe_time_sig_groupBox.setTitle(_translate("TabWidget", "Time signature"))
        self.pe_num_of_staves_label.setText(_translate("TabWidget", "Number of staves:"))
        self.pe_durs_of_ev_label.setText(_translate("TabWidget", "Durations of events:"))
        self.pe_generate_button.setText(_translate("TabWidget", "Generate"))
        self.pe_reset_button.setText(_translate("TabWidget", "Reset"))
        TabWidget.setTabText(TabWidget.indexOf(self.place_events_tab), _translate("TabWidget", "Place events"))

    def rr_division_enabled(self):
        if self.rr_main_dur_comboBox.currentIndex() > 11:
            self.rr_division_groupBox.setEnabled(False)
            self.rr_special_groupBox.setEnabled(False)
            self.rr_division_checkBox.setEnabled(False)
            self.rr_division_checkBox.setChecked(False)
            self.rr_div_irreg_checkBox.setEnabled(False)
            self.rr_div_irreg_checkBox.setChecked(False)
        elif self.rr_main_dur_comboBox.currentIndex() <= 5:
            self.rr_div_irreg_checkBox.setEnabled(True)
            self.rr_division_checkBox.setEnabled(True)
        else:
            self.rr_division_checkBox.setEnabled(True)
            self.rr_div_irreg_checkBox.setEnabled(False)
            self.rr_div_irreg_checkBox.setChecked(False)
            self.rr_special_groupBox.setEnabled(False)

    def ir_time_sig_enabled(self):
        if self.ir_create_radioButton.isChecked():
            self.ir_time_sig_den_label.setEnabled(True)
            self.ir_time_sig_den_spinBox.setEnabled(True)
            self.ir_single_time_sig_checkBox.setChecked(False)
            self.ir_time_sig_groupBox.setEnabled(False)

    def pr_time_sig_enabled(self):
        if self.pr_diff_time_sig_checkBox.isChecked():
            self.pr_diff_time_sig_checkBox.setChecked(False)
            self.pr_time_sig_lst_label.setEnabled(False)
            self.pr_time_sig_lst_lineEdit.setEnabled(False)
            self.pr_num_of_bars_label.setEnabled(True)
            self.pr_num_of_bars_spinBox.setEnabled(True)
            self.pr_time_sig_groupBox.setEnabled(True)

    def rr_reset(self):
        self.rr_division_groupBox.setEnabled(False)
        self.rr_rests_groupBox.setEnabled(False)
        self.rr_main_dur_comboBox.setCurrentIndex(0)
        self.rr_time_sig_first_spinBox.setValue(0)
        self.rr_time_sig_second_spinBox.setValue(0)
        self.rr_num_of_bars_spinBox.setValue(0)
        self.rr_num_of_staves_spinBox.setValue(0)
        self.rr_div_perc_spinBox.setValue(0)
        self.rr_div_parts_spinBox.setValue(0)
        self.rr_den_min_spinBox.setValue(0)
        self.rr_den_max_spinBox.setValue(0)
        self.rr_rests_perc_spinBox.setValue(0)
        self.rr_div_irreg_checkBox.setChecked(False)
        self.rr_div_irreg_checkBox.setEnabled(True)
        self.rr_division_checkBox.setChecked(False)
        self.rr_division_checkBox.setEnabled(True)
        self.rr_rests_checkBox.setChecked(False)

    def ir_reset(self):
        self.ir_op_radiobuttonGroup.setExclusive(False)
        self.ir_create_radioButton.setChecked(False)
        self.ir_generate_radioButton.setChecked(False)
        self.ir_op_radiobuttonGroup.setExclusive(True)
        self.ir_generator_groupBox.setEnabled(False)
        self.ir_generate_button.setEnabled(False)
        self.ir_create_button.setEnabled(False)
        self.ir_get_from_excel_button.setEnabled(False)
        self.ir_time_sig_groupBox.setEnabled(False)
        self.ir_time_sig_den_label.setEnabled(True)
        self.ir_time_sig_den_spinBox.setEnabled(True)
        self.ir_rests_groupBox.setEnabled(False)
        self.ir_num_of_layers_spinBox.setValue(0)
        self.ir_num_of_staves_spinBox.setValue(0)
        self.ir_num_of_bars_spinBox.setValue(0)
        self.ir_time_sig_first_spinBox.setValue(0)
        self.ir_time_sig_second_spinBox.setValue(0)
        self.ir_min_val_spinBox.setValue(0)
        self.ir_max_val_spinBox.setValue(0)
        self.ir_rests_perc_spinBox.setValue(0)
        self.ir_rests_checkBox.setChecked(False)
        self.ir_single_time_sig_checkBox.setChecked(False)
        self.ir_div_last_layer_checkBox.setChecked(True)
        self.ir_time_sig_den_spinBox.setValue(0)

    def pr_reset(self):
        self.pr_op_radiobuttonGroup.setExclusive(False)
        self.pr_gen_rand_ph_radioButton.setChecked(False)
        self.pr_place_points_radioButton.setChecked(False)
        self.pr_op_radiobuttonGroup.setExclusive(True)
        self.pr_rand_phase_gen_groupBox.setEnabled(False)
        self.pr_place_points_groupBox.setEnabled(False)
        self.pr_num_of_bars_label.setEnabled(True)
        self.pr_num_of_bars_spinBox.setEnabled(True)
        self.pr_num_of_bars_spinBox.setValue(0)
        self.pr_time_sig_groupBox.setEnabled(True)
        self.pr_time_sig_first_spinBox.setValue(0)
        self.pr_time_sig_second_spinBox.setValue(0)
        self.pr_min_phase_spinBox.setValue(0)
        self.pr_max_phase_spinBox.setValue(0)
        self.pr_num_of_staves_spinBox.setValue(0)
        self.pr_time_sig_lst_label.setEnabled(False)
        self.pr_time_sig_lst_lineEdit.clear()
        self.pr_time_sig_lst_lineEdit.setEnabled(False)
        self.pr_diff_time_sig_checkBox.setChecked(False)
        self.pr_rests_groupBox.setEnabled(False)
        self.pr_rests_perc_spinBox.setValue(0)
        self.pr_rests_checkBox.setChecked(False)
        self.pr_num_of_imp_spinBox.setValue(0)
        self.pr_phase_filter_checkBox.setChecked(False)

    def pe_reset(self):
        self.pe_main_dur_comboBox.setCurrentIndex(0)
        self.pe_time_sig_first_spinBox.setValue(0)
        self.pe_time_sig_second_spinBox.setValue(0)
        self.pe_num_of_bars_spinBox.setValue(0)
        self.pe_num_of_staves_spinBox.setValue(0)
        self.pe_durs_of_ev_lineEdit.clear()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TabWidget = QtWidgets.QTabWidget()
    ui = Ui_TabWidget()
    ui.setupUi(TabWidget)
    TabWidget.show()
    sys.exit(app.exec_())
